### ISSUE TITLE
ERROR while setting up with SKAFFOLD `listing files:  file pattern [lerna.json] must match at least one file`

### ISSUE THREAD

**Issue by pranta-barua007** [TimWeBill/federation-demo-minikube#16]
in root directory.
just add
 the `skaffold.yaml` file

SKAFFOLD makes development easy by updatig PODS and sync with changes
doc --> https://skaffold.dev/

```
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./manifests/*
build:
  local:
    push: false
  artifacts:
    - image: prantab/accounts
      context: ./services/accounts
      docker: 
        dockerfile: ./dockerfiles/accounts.dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .
    - image: prantab/inventory
      context: ./services/inventory
      docker: 
        dockerfile: ./dockerfiles/inventory.dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .
    - image: prantab/products
      context: products
      docker: 
        dockerfile: ./dockerfiles/products.dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .
    - image: prantab/reviews
      context: reviews
      docker: 
        dockerfile: ./dockerfiles/reviews.dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .
    - image: prantab/gateway
      context: gateway
      docker: 
        dockerfile: ./dockerfiles/gateway.dockerfile
      sync:
        manual:
          - src: './**/*.js'
            dest: .
```
![Screenshot 2022-05-11 222207](https://user-images.githubusercontent.com/52789747/167899356-8a62befc-734a-480d-9325-6af6bcd82df9.png)
